title: The Scala Programming Language

scalaversion: "2.11.1"
devscalaversion: 2.11.1"
# scala_maindownload_unix: "/files/archive/scala-2.11.0.tgz"
# scala_maindownload_windows: "/files/archive/scala-2.11.0.msi"
baseurl: ""
